### ISSUE TITLE
Fails to build with OpenSSL 1.1

### ISSUE THREAD

**Issue by itsoli** [kvspb/nginx-auth-ldap#176]
Trying to build against OpenSSL 1.1 is failing due to fact that the SSL struct in 1.1 is opaque.

```c
ngx_http_auth_ldap_module.c: In function 'ngx_http_auth_ldap_ssl_handshake':
ngx_http_auth_ldap_module.c:1394:79: error: dereferencing pointer to incomplete type 'SSL {aka struct ssl_st}'
         int setcode = SSL_CTX_load_verify_locations(transport->ssl->connection->ctx,
                                                                               ^~
```

**Comment by itsoli** [comment]
https://github.com/kvspb/nginx-auth-ldap/pull/177
