### ISSUE TITLE
Fails to compile after multiple ldap server support was added

### ISSUE THREAD

**Issue by gbjtv** [kvspb/nginx-auth-ldap#13]
I'm compiling this on ubuntu 10.04/lucid and get the following error. Works fine with ubuntu 12.04/precise.

gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -DLDAP_DEPRECATED  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail \
                -o objs/addon/nginx-auth-ldap/ngx_http_auth_ldap_module.o \
                ../nginx-auth-ldap/ngx_http_auth_ldap_module.c
cc1: warnings being treated as errors
../nginx-auth-ldap/ngx_http_auth_ldap_module.c: In function 'ngx_http_auth_ldap_ldap_server_block':
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.satisfy_all' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.require_valid_user' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.require_user' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.require_group' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.group_attribute_dn' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.group_attribute.data' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.group_attribute.len' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.bind_dn_passwd.data' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.bind_dn_passwd.len' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.bind_dn.data' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.bind_dn.len' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.url.data' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.url.len' may be used uninitialized in this function
../nginx-auth-ldap/ngx_http_auth_ldap_module.c:180: error: 'server.ludpp' may be used uninitialized in this function
make[1]: **\* [objs/addon/nginx-auth-ldap/ngx_http_auth_ldap_module.o] Error 1
make[1]: Leaving directory `/tmp/nginx/nginx-1.2.9'
make: **\* [build] Error 2
